services:
  website:
    image: jekyll/jekyll:3.8
    command: ["jekyll", "serve"]
    working_dir: "/srv/matthewlymer.github.io"
    environment:
      - "JEKYLL_DATA_DIR=/srv/matthewlymer.github.io"
    volumes:
      - "./.git:/srv/.git:Z"
      - "./.jekyll/bundle:/usr/local/bundle:Z"
      - "./matthewlymer.github.io:/srv/matthewlymer.github.io:Z"
    ports:
      - "4000:4000/tcp"
