name: Deploy

on: 
  - push

jobs:
  Configure-GCP-Project:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.4
      - working-directory: ./deploy/workload-webapp
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_DEPLOYER_SA }}
        run: terraform init

