name: Deploy

on: 
  - push

jobs:
  Configure-GCP-Project:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_DEPLOYER_SA }}'

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.4

      - working-directory: ./deploy
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_DEPLOYER_SA }}
        run: |
          make push
