name: Deploy

on: 
  - push

jobs:
  Configure-GCP-Project:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_DEPLOYER_SA }}'

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.4

      - name: Build image and push
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_DEPLOYER_SA }}
        run: | # https://stackoverflow.com/a/74795460/507793
          export ACTIONS_CACHE_URL=$(echo "$ACTIONS_ID_TOKEN_REQUEST_URL" | grep -Po 'https://[^/]+/[^/]+/' | sed 's/pipelines/artifactcache/')
          export ACTIONS_RUNTIME_TOKEN=$ACTIONS_ID_TOKEN_REQUEST_TOKEN
          mkdir matthewlymer.github.io/.jekyll-cache
          make -C ./deploy push
